export default [{ title: 'Buy Me!!',
  description: "It's so good!",
  buttonText: 'Buy!' },
{ title: 'Watch Me!!',
  description: 'A great video',
  videoSource: 'https://www.youtube.com/embed/RUCN4Q3egmw',
  buttonText: 'Watch!' },
{ title: 'Go to there!!',
  description: 'A great place to visit',
  externalLink: 'https://www.youtube.com/embed/RUCN4Q3egmw',
  buttonText: 'Go!' },
{ title: 'Read this!',
  description: 'A great thing to read',
  fileSource: '../../static/CandHTeaser.pdf',
  buttonText: 'Go!' },
{ title: 'Email Us!',
  description: 'Get help with email!',
  buttonText: 'Click to send message',
  type: 'email' },
];
