export default [
  { title: 'SMARTDOLLAR®',
    subtitle: 'Powered by Ramsey Solutions',
    videoSource: 'https://www.youtube.com/embed/RUCN4Q3egmw',
    thumbnail: '../../static/video.jpg',
    button1Text: 'Log-in & Learn',
    button2Text: 'Request Access',
    type: 'video' },
  { title: 'WELFIE® BLOG',
    subtitle: 'Useful stuff, not fluff',
    thumbnail: '../../static/blog.png',
    buttonText: 'View All Posts',
    type: 'blog' },
  { title: 'WELFIE® SCORE',
    thumbnail: '../../static/score.png',
    button1Text: 'Details',
    button2Text: 'Update',
    type: 'score' },
  { title: 'INVEST',
    description: 'Request the Portfolio Builder workbook with recommended allocations & money managers or have your portfolio professionally managed.',
    button1Text: 'Get Prof. Help*',
    button2Text: 'Go to 401(k)',
    type: 'invest' },
  { title: 'ORGANIZE',
    description: 'Improved financial wellness begins with better organization.',
    buttonLabel: 'Free PDF templates & kits',
    buttonText: 'Download',
    type: 'organize' },
  { title: 'COACHING',
    description: 'Get encouragement, ideas, & accountability tackling debt, facing emergencies, budgeting, planning a bright future, & improving savings.',
    buttonLabel: '1 Month Free; $50 / month',
    buttonText: 'Get Started*',
    type: 'coaching' },
  { title: 'GET THE BASICS',
    description: 'The starter financial wellness service package provides some basic & compassionate tools to help put you on the path to improvement.',
    buttonLabel1: '$500 one-time',
    buttonLabel2: '(sponsored by your employer)',
    button1Text: 'Learn More *',
    button2Text: 'Get PLFS BLUE*',
    type: 'basics' },
  { title: 'PLAN',
    description: 'All the benefits of Blue PLUS an affordable financial planning solution with your own designated planning associate to make the journey with you...& much more.',
    buttonLabel1: 'From $300 150 / year',
    buttonLabel2: 'View cost waiver criteria',
    button1Text: 'Learn More *',
    button2Text: 'Get PLFS GOLD *',
    type: 'gold' },
  { title: 'ADVICE & SUPPORT',
    description: 'All the benefits of GOLD PLUS your very own licensed professional sounding-board for Q&A & direction',
    buttonLabel1: 'From $499 $299 / year',
    buttonLabel2: 'View cost waiver criteria',
    button1Text: 'Learn More *',
    button2Text: 'Get PLFS PLAT. *',
    type: 'advice' },
];
